### PR TITLE
Update Document

### LINKED ISSUE #1: lol finish the darn document

### PR DESCRIPTION
**Pull request by Rekunan**
Closes #1 

- [x] Create skeleton
- [x] Check if I missed anything
- [x] Remove all files from repo
	- [x] Remove all .osk's
	- [x] Remove all images
- [x] Use Releases for .osk files
- [x] Use external links for screenshots
- [x] Final check if I missed anything

### CODE REVIEW

**Comment by ILW8** [comment]
SHEEESH

**Comment by Rekunan** [comment]
force-pushed to fix commit message

**Comment by Rekunan** [comment]
i tested in a priv repo to make sure the release dl links work

some notes: spaces and any special characters that "don't work" get converted to . and if multiple are next to each other, they all get converted to one .
ex: 
`- # owoTuna {1.4} 『Mathi』 # -.osk` -> `-.owoTuna.1.4.Mathi.-.osk`
`Minimal+Weeb+-+Noel+v1.3.osk` gets no change

when I get the time to i'll upload all the .osk's as a release (unless someone else does it first) so the release dl links can be tested, but otherwise, this is it.

**Comment by Rekunan** [comment]
blocked until release is made, feel free to review if you want

**Comment by Rekunan** [comment]
GitHub PR Draft to Completion Any% speedrun

**Review by ILW8 — APPROVED** [review]
Holy poggers, nice work.

**Pull request merged**
